/**************************
 * 
 *************************************/
export interface Db_Culture_pms {
    code_culture: string, 
    id_parce: string, 
    id_var: string,
    id_saison: string,
    annee_du: string,
    ddp: string,
    dt_creation: string,
    dt_modification: string,
    qsa : number,
    img_fact: string,
    dds: string,
    sfce: number,
    sc: string,
    ea_id_variette: string,
    ea_autres: string,
    statuts: string,
    Etat: string
}
export interface Db_suivi_pms {
    id: string,
    code_culture: string, 
    ddp: string, 
    stc: string, 
    ec: string, 
    ex: string, 
    pb: string,
    img_cult: string, 
    name: string,
    path: string,
    controle: string,
    declaration: string,
    etat: string
}
export interface AddMepBloc {
    code_culture: string, 
    id_parce: string, 
    id_espece: string, 
    id_var: string, 
    id_saison: string, 
    annee_du: string, 
    ddp: string, 
    qso: string, 
    dt_distribution: string,
    dds: string, 
    sfce: number, 
    nbre_ligne: number,
    long_ligne: number,
    usage: string,
    sc: string, 
    ea_autres: string, 
    ea_id_variette: string,
    dt_creation: string, 
    dt_modification: string, 
    status: string, 
    etat: string, 
    id_equipe: number,
    type: string
}
export interface UpdateSuiviBloc {
    code_sv: string, 
    id_culture: string, 
    ddp: string,
    stc: string, 
    ec: string,
    ql: number, 
    qr: number, 
    long_ligne: number, 
    nbre_ligne: number, 
    nbre_pied: number, 
    hauteur: number,
    img_cult: string, 
    dt_capture: string,
    ex: string,
    dt_creation: string,
    dt_modification: string,
    etat: string
}
export interface UpdateBenef {
    code_benef: string,
    img_benef: string,
    nom: string,
    prenom: string,
    sexe: string,
    dt_nais: string,
    dt_nais_vers: string,
    surnom: string,
    cin: number,
    dt_delivrance: string,
    lieu_delivrance: string,
    img_cin: string,
    contact: string,
    id_fkt: string,
    id_commune: string,
    village: string,
    dt_Insert: string, 
    etat: string,
    statut: string
}
export interface UpdateBenefActivPr {
    code_pr: string, 
    id_proj: string, 
    id_activ: number, 
    id_benef: string, 
    id_bloc: string, 
    code_achat: string, 
    id_collaborateur: number, 
    id_tech: number, 
    etat: string,
    status: string
}