export interface Association {
    id_prjt: string,
    code_proj: string, 
    nom_pr: string, 
    id_fkt:  string, 
    nom_fkt: string,
    code_ass: string, 
    nom_ass: string,
    id_tech: number, 
    technicien: string,
    nb_benef: number, 
    nom_pa: string,
    prenom: string,
    sexe: string,
    cin: number,
    dt_delivrance: string,
    lieu_delivrance: string,
    img_benef: Blob,
    surnom: string,
    status: string
}
export interface Benef_activ_pms {
    id_activ: number,
    intitule: string,
    id_proj: string,
    nom_pr: string,
    fkt_association: string,
    id_association: string,
    nom_ass: string,
    code_benef_pms: string,
    code_parce: string,
    nb_parcelle: number,
    sum_superf: number,
    id_benef: string,
    code_benef: string,
    img_benef: string,
    nom_benef: string,
    prenom: string,
    sexe: string,
    dt_nais: string,
    surnom: string,
    cin: number,
    dt_delivrance: string,
    lieu_delivrance: string,
    img_cin: Blob,
    contact: string,
    id_fkt: string,
    adress: string,
    id_collaborateur: string,
    nom_collab: string,
    statut: string
}
export interface Local_Parcelle {
    fkt_association: string,
    id_association: string,
    nom_ass: string,
    code_benef_pms: string,
    nom: string,
    prenom: string,
    code_parce: string,
    id_benef: string,
    ref_gps: string,
    lat: string,
    log: string,
    superficie: string,
    id_fkt: string,
    status: string
}
export interface Loc_Commune {
    nom_reg: string,
    id_dist: string, 
    nom_dist: string,  
    code_com: string, 
    nom_com: string
}
export interface Loc_Bloc {
    code_bloc: string,
    nom_bloc: string,
    id_prjt: string,
    id_tech: string,
    status: string,
    id_fkt: string,
    nom_fkt: string,
    code_com: string,
    nom_com: string,
    nb_fkt: string
}
export interface Local_benef_activ_bl {
    code_benef_bl: string,
    nom: string,
    prenom: string,
    sexe: string,
    dt_nais: string,
    surnom: string,
    cin: string,
    dt_delivrance: string,
    lieu_delivrance: string,
    img_cin: string,
    contact: string,
    nom_com: string,
    id_fkt: string,
    nom_fkt: string,
    statut_benef: string,
    id_proj: string,
    id_activ: number,
    id_benef: string,
    id_bloc: string,
    nom_bloc: string,
    id_collaborateur: string,
    nom_collab: string,
    status: string,
    nb_parce: number,
    sum_superficie: number
}
export interface Local_bloc_zone {
    code: number,
    id_bloc: string,
    nom_bloc: string,
    nom_com: string,
    id_fkt: string,
    nom_fkt: string,
    id_km: string,
    nom: string,
    prenom: string
}
export interface Local_bloc_parce {
    id_bloc: string,
    nom_bloc: string,
    code_benef_bl: string,
    nom: string,
    prenom: string,
    code_parce: string,
    ref_gps: string,
    lat: number,
    log: number,
    superficie: number,
    anne_adheran: string,
    status: string
}